### ISSUE TITLE
Dead link in usage instructions

### ISSUE THREAD

**Issue by ctkelley** [HolyLab/HolyLabRegistry#137]
The link to the manual in

(The ] enters Pkg mode when you type it at the REPL prompt, see https://docs.julialang.org/en/latest/stdlib/Pkg/.)

does not seem to work. Should it be https://docs.julialang.org/en/v1/stdlib/Pkg/ ?

**Comment by kdw503** [comment]
Thanks

**Comment by timholy** [comment]
Closed by #138
