### ISSUE TITLE
Install CompatHelper across organization?

### ISSUE THREAD

**Issue by IanButterworth** [HolyLab/HolyLabRegistry#156]
It would be helpful for compat to be more systematically updated. 
Could CompatHelper be installed across the public packages in this organization?
https://github.com/JuliaRegistries/CompatHelper.jl

Stating the obvious, but once installed it would be great if CompatHelper PRs could be merged promptly and patch updates released immediately afterwards.

@timholy, if I can help at all I'm happy to. Perhaps I could join the org as a maintenance/compat updates-only contributor? (edit: I mean a member that can only view public repos)

**Comment by Octogonapus** [comment]
@timholy @kdw503 Ian and I would be happy to spend some of our time helping maintain the code in this organization. Please let us know if there is any way we can help, even if it's just doing compat updates. Thank you! :)

**Comment by IanButterworth** [comment]
@kdw503 would it be possible to merge the above PRs so their their crons can be run tonight? It'd be nice to wrap this up

**Comment by kdw503** [comment]
@timholy Do you think is it ok to apply this CompatHelper to those packages?

**Comment by IanButterworth** [comment]
Just to explain. For each of them I took the template from https://juliaregistries.github.io/CompatHelper.jl/dev/
and added your `registry_add` step from CI.yml

**Comment by IanButterworth** [comment]
Bump. @timholy I'm happy to have a call/slack chat if it would be more efficient (I sent you an email too)

**Comment by kdw503** [comment]
@ianshmean All merged. Thank you for the contributions and sorry for the late.

**Comment by timholy** [comment]
CompatHelper should be on for most or all repos.
