### ISSUE TITLE
Install TagBot across all repos

### ISSUE THREAD

**Issue by IanButterworth** [HolyLab/HolyLabRegistry#165]
As demonstrated here https://github.com/HolyLab/HolyLabRegistry/pull/164#issuecomment-902378441 HolyLabRegistry is now able to trigger TagBot on the repo with the new release

If you agree @timholy, we could do a mass install of the TagBot.yml from here https://github.com/HolyLab/RegisterDeformation.jl/blob/v0.4.3/.github/workflows/TagBot.yml

(at the same time it would be efficient to also add CompatHelper i.e. https://github.com/HolyLab/HolyLabRegistry/issues/156)

**Comment by timholy** [comment]
Strongly agreed! We're happy to do it, and can get to it by next week when @kdw503 is back. If you're in a hurry, though, of course it's fine if you'd rather just do it.

**Comment by IanButterworth** [comment]
I'm actually heading off on vacation for a week so that sounds good 👍

**Comment by timholy** [comment]
We've installed TagBot everywhere
