### ISSUE TITLE
Adding SSH keys on Travis

### ISSUE THREAD

**Issue by timholy** [HolyLab/HolyLabRegistry#42]
It seems that `travis-ci.com` only lets you add an SSH key if you initially created the package. For instance, I can add new SSH keys for `BoundedRegistration.jl`; I can see a key added by @kdw503 for `RegisterOptimize.jl`, and there's also a trash-can icon so I could delete it, but no obvious way for me to add a new key; and on `RegisterQD.jl` there is no SSH key and I see no buttons to add one. 

If there isn't an easy fix, this could be a long-term problem as people leave the lab.

**Comment by kdw503** [comment]
I forgot to set member privilege on those packages. I think that could cause the problem. Now, I set up all those setting in the BlockRegistration related packages. About  `RegisterQD.jl`, that seems because the package is a public one.
