### ISSUE TITLE
TOML parse error

### ISSUE THREAD

**Issue by Cody-G** [HolyLab/HolyLabRegistry#79]
Has anyone encountered the TOML parsing error I describe in https://github.com/JuliaLang/Pkg.jl/issues/1017?  It seems no one else in the Julia community is experiencing it so I wonder if it's related to our registry.

Edit: the branch for [this PR](https://github.com/HolyLab/EmpiricalTiming.jl/pull/3) reliably triggers the error on Travis.

**Comment by sbromberger** [comment]
I'm seeing it too using my own private registry.

**Comment by Cody-G** [comment]
Hopefully https://github.com/HolyLab/HolyLabRegistry/pull/81 will prevent accidental introduction of invalid TOML files into the registry, closing for now.
